name: Branches CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

  workflow_dispatch: # Enable manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update NPM
        run: npm -g install npm

      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: .npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install NPM dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Build Drinklist
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update NPM
        run: npm -g install npm

      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: .npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install NPM dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Lint Drinklist
        run: npm run lint

  docker:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Save lowercase repository name in ENV
        run:
          echo "repo_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set docker tags
        run: |
          TAGS=ghcr.io/${{ env.repo_name }}:${{ github.sha }}
          TAGS=$TAGS,ghcr.io/${{ env.repo_name }}:${{ github.ref_name }}
          echo "docker_tags=$TAGS" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.docker_tags }}
